language: python

python:
  - "2.7"
  - "3.5"

env:
  - ARANGODB_VERSION: v2.8.11
  - ARANGODB_VERSION: v3.0.3

before_install:
- curl -s -L https://raw.githubusercontent.com/brennv/arangodb-travis/$ARANGODB_VERSION/setup_arangodb.sh -o setup_arangodb.sh
- chmod +x setup_arangodb.sh
- ./setup_arangodb.sh

install: pip install tests/python_requirements.txt

script: python -m unittest discover tests/
